<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;
use function Breakdance\Elements\PresetSections\getPresetSection;


\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Gamezone",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Gamezone extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'section';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Gamezone';
    }

    static function className()
    {
        return 'autogenerated-bce-gamezone';
    }

    static function category()
    {
        return 'other';
    }

    static function badge()
    {
        return ['backgroundColor' => 'var(--white)', 'textColor' => 'var(--black)', 'label' => 'Gamezone'];
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        // Start session if not already started
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }
        
        // Fetch seasons and inject as a global variable
        if (function_exists('get_field')) {
            $seasons = get_field('seasons', 'option') ?: [];
            error_log('CACHE BUST v3 - First season season_data type: ' . gettype($seasons[0]['season_data'] ?? 'not set'));
            if (isset($seasons[0]['season_data'][0])) {
                error_log('First season_data item type: ' . gettype($seasons[0]['season_data'][0]));
                error_log('First season_data item: ' . print_r($seasons[0]['season_data'][0], true));
            }
            // Initialize the Session variables if not already set
            if (!isset($_SESSION['year']) && !empty($seasons)) {
                $_SESSION['year'] = $seasons[0]['season_name'];
            }
            
            // Convert season_data - handle both WP_Post objects and post IDs
            $seasons_converted = [];
            foreach ($seasons as $season) {
                $season_copy = $season;
                if (isset($season['season_data']) && is_array($season['season_data'])) {
                    $posts = [];
                    foreach ($season['season_data'] as $item) {
                        // Check if it's already a WP_Post object
                        if (is_object($item) && isset($item->ID)) {
                            $posts[] = [
                                'ID' => $item->ID,
                                'post_title' => $item->post_title,
                                'post_name' => $item->post_name,
                                'meta' => get_post_meta($item->ID),
                            ];
                        } 
                        // Otherwise treat as post ID
                        elseif (is_numeric($item)) {
                            $post = get_post($item);
                            if ($post) {
                                $posts[] = [
                                    'ID' => $post->ID,
                                    'post_title' => $post->post_title,
                                    'post_name' => $post->post_name,
                                    'meta' => get_post_meta($post->ID),
                                ];
                            }
                        }
                    }
                    $season_copy['season_data'] = $posts;
                }
                $seasons_converted[] = $season_copy;
            }
            $seasons = $seasons_converted;
        } else {
            $seasons = [];
        }

        $competitions = [];
        if(isset($_SESSION['year']) && !empty($_SESSION['year'])) {
            $seasons_for_comp = get_field('seasons', 'option') ?: [];
            foreach ($seasons_for_comp as $season) {
                if ($season['season_name'] === $_SESSION['year']) {
                    if (isset($season['season_data']) && is_array($season['season_data']) && count($season['season_data']) > 0) {
                        // Convert competitions data like we did for seasons
                        // debug_to_console( 'in' );
                        $competitions_temp = [];
                        foreach ($season['season_data'] as $item) {
                            // debug_to_console( 'item: ' . $item );
                            if (is_object($item) && isset($item->ID)) {
                                $competitions_temp[] = [
                                    'ID' => $item->ID,
                                    'post_title' => $item->post_title,
                                    'post_name' => $item->post_name,
                                    'meta' => get_post_meta($item->ID),
                                    'competition_id' => get_post_meta( $item->ID, 'season_id', true ),
                                ];
                            } elseif (is_numeric($item)) {
                                $post = get_post($item);
                                // debug_to_console( 'title: ' . $post->post_title  );
                                if ($post) {
                                    $competitions_temp[] = [
                                        'ID' => $post->ID,
                                        'post_title' => $post->post_title,
                                        'post_name' => $post->post_name,
                                        'meta' => get_post_meta($post->ID),
                                        'competition_id' => get_post_meta( $post->ID, 'season_id', true ),
                                    ];
                                }
                            }
                        }
                        $competitions = $competitions_temp;
                        
                        // Set competition_id and competition_post_id to first competition if not set
                        if ((!isset($_SESSION['competition_id']) || empty($_SESSION['competition_id'])) && !empty($competitions)) {
                            $_SESSION['competition_post_id'] = $competitions[0]['ID'];
                            $competition_id = get_post_meta( $competitions[0]['ID'], 'season_id', true );
                            $_SESSION['competition_id'] = $competition_id;
                        }
                        break;
                    }
                }
            }
        }
        
        // Fetch grades based on competition_id from session
        $grades = [];
        // unset($_SESSION['competition_id']);
        if(isset($_SESSION['competition_post_id']) && !empty($_SESSION['competition_post_id'])) {
            $grades = get_ordered_seasons_grades( $_SESSION['competition_post_id'] );
            if (!empty($grades) && !isset($_SESSION['grade_id'])) {
                $_SESSION['grade_id'] = $grades[0]['id'];
            }
        } else {
            debug_to_console( 'No competition id set in session, determining from year.' );
            $seasons = get_field('seasons', 'option') ?: [];
            foreach( $seasons as $season) {
                if ($season['season_name'] === $_SESSION['year']) {
                    if (isset($season['season_data']) && is_array($season['season_data']) && count($season['season_data']) > 0) {
                        $_SESSION['competition_post_id'] = $season['season_data'][0];

                        $grade_order = get_post_meta( $season['season_data'][0], 'season_id', true );
                        if (!empty($grade_order)) {
                            $_SESSION['grade_id'] = $grade_order[0];
                            debug_to_console( 'set grade id to: ' . $_SESSION['grade_id'] );
                        }
                        // break;
                    }
                }
            }
            $grades = get_ordered_seasons_grades( $_SESSION['competition_post_id'] );
        }
        
        // Fetch rounds and matches
        // $_SESSION['grade_id'] = '5a078cfe-dcc4-492c-b8f5-cab992ee27a2';
        $matches_data = [];
        if (isset($_SESSION['grade_id']) && !empty($_SESSION['grade_id']) && function_exists('get_seasons_rounds')) {
            $rounds = get_seasons_rounds($_SESSION['grade_id']);
            
            if ($rounds !== "No rounds found for this grade.") {
                $matches_to_show = get_field('matches') ?: 6;
                
                // Set round_id if not set
                if (!empty($rounds) && isset($rounds[0]['id'])) {
                    if (!isset($_SESSION['round_id']) || empty($_SESSION['round_id']) || $_SESSION['round_id'] == 'null') {
                        $_SESSION['round_id'] = $rounds[0]['id'];
                    }
                }
                
                $position = 1;
                $delayStart = 0.125;
                
                // Get display setting from content controls
                $display = isset($propertiesData['content']['settings']['display']) ? $propertiesData['content']['settings']['display'] : 'combined';
                
                if ($display == 'matches') {
                    // Show matches for selected round only
                    $delayStart = 0.25;
                    foreach ($rounds as $round) {
                        if (isset($_SESSION['round_id']) && $_SESSION['round_id'] == $round['id']) {
                            if (isset($round['matches'])) {
                                foreach ($round['matches'] as $match) {
                                    $match['delay'] = $delayStart * $position;
                                    $matches_data[] = $match;
                                    $position++;
                                }
                            }
                        }
                    }
                } else {
                    // Show limited matches from all rounds
                    foreach ($rounds as $round) {
                        if (isset($round['matches']) && $position <= $matches_to_show) {
                            foreach ($round['matches'] as $match) {
                                if ($position <= $matches_to_show) {
                                    $match['delay'] = $delayStart * $position;
                                    $matches_data[] = $match;
                                    $position++;
                                }
                            }
                        }
                    }
                }
            }
        }

        // Render matches HTML
        $matches_html = '';
        if (!empty($matches_data) && is_array($matches_data) && function_exists('display_match_summary')) {
            ob_start();
            foreach ($matches_data as $match) {
                display_match_summary(
                    $match,
                    $_SESSION['competition_id'] ?? '',
                    $_SESSION['grade_id'] ?? '',
                    $match['delay'] ?? 0
                );
            }
            $matches_html = ob_get_clean();
        }

        $ladders_data = [];
        if (isset($_SESSION['grade_id']) && !empty($_SESSION['grade_id']) && function_exists('get_ladder')) {
            $ladders_data = get_ladder($_SESSION['grade_id'], 'overall' );
        }

        // Render ladders HTML
        $ladders_html = '';
        if (!empty($ladders_data) && is_array($ladders_data)) {
            $ladderTypes = get_ladder_types( $_SESSION['grade_id'] );
            $type = 'overall';
            $ladder = get_ladder( $_SESSION['grade_id'], $type );
            $headers = $ladder[0];
            $standings = $ladder[1];
            $position = 1;
            ob_start();
            ?>
            <div class="gamezone__ladder-list-wrapper">
                <div class="gamezone__ladder-line headings">
                    <div class="gamezone__ladder-line-item" data-heading="position">
                        <span class="gamezone__ladder-header-title">&nbsp;</span>
                    </div>
                    <div class="gamezone__ladder-line-item" data-heading="team-name">
                        <span class="gamezone__ladder-header-title">Team</span>
                    </div>
                    <?php foreach( $headers as $header ) : ?>
                    <div class="gamezone__ladder-line-item" data-heading="<?php echo $header['key']; ?>">
                        <span class="gamezone__ladder-header-title"><?php echo $header['shortName']; ?></span>
                    </div>
                    <?php $headings[] = $header['key']; ?>
                    <?php endforeach; ?>
                </div>
                <?php foreach( $standings as $standing ) : ?>
                <?php 
                    $logo = get_team_logo( $standing['team']['id'], $_SESSION['competition_id'], $cursor = 'null' );

                    $delay = $delayStart * $position;
                ?>
                <div class="gamezone__ladder-line wow fadeInUp row-<?php echo $position; ?>" data-wow-delay="<?php echo $delay; ?>s">
                  <div class="gamezone__ladder-line-item" data-heading="position">
                    <p><?php echo $position; ?></p>  
                  </div>
                  <div class="gamezone__ladder-line-item" data-heading="team-name">
                    <div class="gamezone__ladder-team">
                      <div class="gamezone__ladder-line-logo">
                        <?php if( $logo != 'NOTHING Error' ) : ?>
                          <img src="<?php echo $logo; ?>" alt="<?php echo $standing['team']['name']; ?> logo" class="gamezone__ladder-team-logo">
                        <?php else : ?>
                          <div class="gamezone__ladder-team-logo no-image"></div>
                        <?php endif; ?>
                      </div>
                      <span class="gamezone__ladder-team-name"><?php echo $standing['team']['name']; ?></span>
                    </div>  
                  </div>
                  <?php $count = 0; ?>
                  <?php foreach( $standing['values'] as $value ) : ?>
                    <div class="gamezone__ladder-line-item" data-heading="<?php echo $headings[$count]; ?>">
                      <div class="gamezone__ladder-line-item-wrapper">
                        <span class="gamezone__ladder-team-value"><?php echo $value; ?></span>
                      </div>
                    </div>
                    <?php $count++; ?>
                  <?php endforeach; ?>
                  <?php $position++; ?>
                </div>
              <?php endforeach; ?>
            </div>
            <?php
            $ladders_html = ob_get_clean();
        }
        
        $template = file_get_contents(__DIR__ . '/html.twig');
        
        // Debug: Check the first season's first post
        if (isset($seasons[0]['season_data'][0])) {
            error_log('First post before JSON: ' . print_r($seasons[0]['season_data'][0], true));
        }
        
        // Encode data properly for Twig with newline escaping
        $seasons_json = json_encode($seasons, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES);
        if ($seasons_json === false) {
            error_log('Failed to encode seasons JSON: ' . json_last_error_msg());
            $seasons_json = '[]';
        }
        $session_json = json_encode($_SESSION, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES);
        $competition_json = json_encode($competitions, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES);
        $grades_json = json_encode($grades, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES);
        $matches_json = json_encode($matches_data, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES);
        $ladders_json = json_encode($ladders_html, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES);
        
        // For HTML content, escape for safe embedding in Twig without unicode encoding
        $matches_html_escaped = str_replace(['\\', '"', "\n", "\r"], ['\\\\', '\\"', '\\n', '\\r'], $matches_html);
        $ladders_html_escaped = str_replace(['\\', '"', "\n", "\r"], ['\\\\', '\\"', '\\n', '\\r'], $ladders_html);
        
        // Generate a unique block ID
        $block_id = 'gamezone-' . uniqid();
        
        // Inject at the start of the template
        $injected_vars = "{% set block_id = '" . $block_id . "' %}\n";
        $injected_vars .= "{% set seasons_data = " . $seasons_json . " %}\n";
        $injected_vars .= "{% set session = " . $session_json . " %}\n";
        $injected_vars .= "{% set competitions_data = " . $competition_json . " %}\n";
        $injected_vars .= "{% set grades_data = " . $grades_json . " %}\n";
        $injected_vars .= "{% set matches_data = " . $matches_json . " %}\n";
        $injected_vars .= "{% set matches_html = \"" . $matches_html_escaped . "\" %}\n";
        $injected_vars .= "{% set ladders_html = \"" . $ladders_html_escaped . "\" %}\n";
        
        return $injected_vars . $template;
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return false;
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [getPresetSection(
            "EssentialElements\\typography",
            "Typography",
            "typography",
            ['type' => 'popout']
        )];
    }

    static function contentControls()
    {
        return [c(
        "settings",
        "Settings",
        [c(
        "year",
        "Year",
        [],
        ['type' => 'dropdown', 'layout' => 'vertical', 'items' => [['text' => '2025/26', 'value' => '2025/26'], ['text' => '2024/25', 'value' => '2024/25'], ['text' => '2023/24', 'value' => '2023/24'], ['text' => '2022/23', 'value' => '2022/23']]],
        false,
        false,
        [],
        
      ), c(
        "display",
        "Display",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'combined', 'text' => 'Combined'], ['text' => 'Matches', 'value' => 'matches'], ['text' => 'Ladders', 'value' => 'ladders']]],
        false,
        false,
        [],
        
      ), c(
        "matches_to_display",
        "Matches to Display",
        [],
        ['type' => 'number', 'layout' => 'vertical', 'rangeOptions' => ['min' => 1, 'max' => 6, 'step' => 1]],
        false,
        false,
        [],
        
      )],
        ['type' => 'section'],
        false,
        false,
        [],
        
      ), c(
        "heading",
        "Heading",
        [c(
        "heading",
        "Heading",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
        
      ), c(
        "icon",
        "icon",
        [],
        ['type' => 'icon', 'layout' => 'vertical'],
        false,
        false,
        [],
        
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
        
      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return false;
    }

    static function settings()
    {
        return ['requiredPlugins' => ['ACF']];
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return false;
    }

    static function nestingRule()
    {
        return ['type' => 'final'];
    }

    static function spacingBars()
    {
        return [];
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function availableIn()
    {
        return ['breakdance'];
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return false;
    }

    static function additionalClasses()
    {
        return false;
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return false;
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}
